name: Prettier
  # You may pin to the exact commit or the version.
  # uses: creyD/prettier_action@0b655e298cc5c8477c9df9e60dfb6cd5d79f3055
  # This action works with pull requests and pushes
  

on:
  ## this ensures the update runs against the fork branch
  pull_request:
  push:
    branches:
      - develop
jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses:
          actions/checkout@v2
          # Make sure the actual branch is checked out when running on pull requests
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          persist-credentials: false
      - name: Prettify code
        run: npm i
        run: npx prettier --check .
